### ISSUE TITLE
Where is the bluetooth broadcast part

### ISSUE THREAD

**Issue by donly** [fokx/temperature_relay#1]
Hi, thank you for sharing this project.

As you said in the README, `This is a Keil C51 project using SHT3X temperature sensor and broadcast data via bluetooth to mobile device.`

But I can't see the code of bluetooth part, can you share it.

**Comment by fokx** [comment]
Thanks for your interest.
As C51 does not provide Bluetooth capabilities, I use a HC-0X Bluetooth PCB module(has a TI Bluetooth chip on it) in my project, which communicates with the C51 microcontroller via serial port, as you can see in: https://github.com/fokx/temperature_relay/blob/754279fadb035a406225b446d12e618d9cc60029/src/main.c#L62
